### ISSUE TITLE
Getting invalid swift manifest and wrong target when building for iOS 

### ISSUE THREAD

**Issue by heyshowshana** [ttypic/swift-klib-plugin#35]
Hello, we've run into a curious issue, while trying to use your plugin in our KPM project.

# Steps to reproduce:

1. Add the plugin + expose swift class to a KPM project
2. Build it from Xcode `15.4` or `15.3.`
3. You will get an `invalid swift manifest` error as it builds from MacOS, even though the target is set to build for iPhone Simulator.

```
> Task :ourProject:swiftklibKCryptoIosSimulatorArm64
'swiftbuild': Invalid manifest (compiled with: ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/xg/9cxqrskx3zq5503j26vb1fn00000gn/T/TemporaryDirectory.EDusGx/vfs.yaml", "-L", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-target", "arm64-apple-macosx13.0", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk", "-F", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks", "-I", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-L", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-swift-version", "5", "-I", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk", "-package-description-version", "5.5.0", "/Users/username/outproject-mobile/outproject/build/swiftklib/KCrypto/iosSimulatorArm64/swiftBuild/Package.swift", "-Xfrontend", "-disable-implicit-concurrency-module-import", "-Xfrontend", "-disable-implicit-string-processing-module-import", "-o", "/var/folders/xg/9cxqrskx3zq5503j26vb1fn00000gn/T/TemporaryDirectory.h3z7Ne/swiftbuild-manifest"])

fatalError

/Users/username/ivy-mobile/iOS/<unknown>:1:1: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX'
```

Hypothesis: Xcode executes task `:ivy:embedAndSignAppleFrameworkForXcode`, that build all the Kotlin files, and triggers `:ivy:swiftklibKCryptoIosSimulatorArm64`, however environment variables containing the build target are not passed or misinterpreted by the swiftklibKCryptoIosSimulatorArm64 task, therefore, when is executed from the Xcode, it builds for MacOS target, which is rejected in next step, as the rest of the project is for iPhone Simulator.

We also observe the same behavior when building for iOS generic devices (e.g., production build).

## Strange workaround in Android Studio:

Doing Gradle Sync in Android Studio performs these tasks:
```
> Task :ivy:swiftklibKCryptoIosArm64
> Task :ivy:cinteropKCryptoIosArm64
> Task :ivy:swiftklibKCryptoIosSimulatorArm64
> Task :ivy:cinteropKCryptoIosSimulatorArm64
> Task :ivy:swiftklibKCryptoIosX64
> Task :ivy:cinteropKCryptoIosX64
```

After these tasks have run, the XCode build succeeds. This is the output of Kotlin build executed by Xcode -- `UP-TO-DATE`, therefore skipping the KLib build as it has been already done from the Android Studio environment.

> Task :ivy:swiftklibKCryptoIosSimulatorArm64 UP-TO-DATE
> Task :ivy:cinteropKCryptoIosSimulatorArm64 UP-TO-DATE

### What is strange here?

- From my understanding, these tasks should NOT be executed at all for the Android environment. (Or maybe they should, but only on MacOS, so Android Studio can see contents of references Swift files, and Intelli Sence works)
- For some reason, it builds for the correct target, even when there are missing Xcode environment variables defining the target, as it is built inside Android Studio.
- As this Swift-KLib build is always triggered, it blocks the build on our Linux CI, where we build Android binaries, referencing separate issue: https://github.com/ttypic/swift-klib-plugin/issues/16

**Comment by jvondermarck** [comment]
I have the same issue

**Comment by jvondermarck** [comment]
I figured it out why there is this error. This` invalid swift manifest` error happens **when you edit the code inside your Swift** `group`. 

### To avoid the error to happen you need follow these steps

1. Comment in your build.gradle file the swiftklib section and the create part :
```kotlin

kotlin {
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach {
        it.compilations {
            val main by getting {
                cinterops {
                    //create("HelloSwift")
                }
            }
        }
    }

    //...
}

/*
swiftklib {
    create("HelloSwift") {
        path = file("native/HelloSwift")
        packageName("com.ttypic.objclibs.greeting")
    }
}
*/
```

2. Build your project : it should now work again (you could also clean your project but it is not mandatory)
3. Then uncomment your code and you will not have the error anymore

> [!CAUTION]
> I know, I know, it is just a workaround but at least you will stop exploding your head whenever this error happens... (because I did)... :)

**Comment by wh173d3v11** [comment]
This PR will solve the above issues - #45

**Comment by jvondermarck** [comment]
Awesome @wh173d3v11 !! 💪🏽

**Comment by IlyaGulya** [comment]
@jvondermarck @heyshowshana Regarding issue that plugin runs on non-macos hosts - I've finally merged the fix. It is available in 0.6.5 release (https://github.com/ttypic/swift-klib-plugin/releases/tag/v0.6.4)
Please try this one and let me know if problem persists

**Comment by wh173d3v11** [comment]
@heyshowshana  @jvondermarck  resolved by updating Xcode to version 16.0, update the Kotlin library to version 2.0.21 and resync your project. You can close this issue.

**Comment by jvondermarck** [comment]
Hello, I am not working in the company where I was before, so I can't test it, so I will close the issue, thank you for your contribution !!

**Comment by JesusMcCloud** [comment]
This issue crops up when using a composite build, i.e. when the CMP app you are trying to build includes a KMP library and this library uses the swift-klib-plugin, for example: [here](https://github.com/a-sit-plus/signum/tree/6f28d816d068c0cea3089389f04e659157c08c03).

**Comment by JesusMcCloud** [comment]
> This issue crops up when using a composite build, i.e. when the CMP app you are trying to build includes a KMP library and this library uses the swift-klib-plugin, for example: [here](https://github.com/a-sit-plus/signum/tree/6f28d816d068c0cea3089389f04e659157c08c03).

This might have been a false alarm, since the kotlin versions of the CMP app and the included library were not aligned.
I'm still keeping my comment, because everything related to XCode (and its command-line tools) is much more fragile than it should be. For the sake of completeness: I also added swift-klib to the CMP app with a Swift file that contains a class with NOOP function, so I could align the swift-klib config between app and included KMP library. No idea whether this contributed to the fix or not, because after removing it, it continued working (see also the info dropped in #45).

**Comment by michalgwo** [comment]
Still an issue on Xcode 16.2 and Kotlin 2.1.20. @jvondermarck's approach didn't work either

**Comment by savvasdalkitsis-dojo** [comment]
Same here on Xcode 16.3. Workaround didn't work. This is very frustrating :(

**Comment by GoodSir42** [comment]
having the same issue here. Manually calling the tasks invoked at the project sync seems to do the trick on the CI host, but this should be fixed somehow. Using xcode 16.2 here as 16.3 does not build at all with KMP right now 😅 I know a fix is in the works for that.
